apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: fcg
type: Opaque
stringData:
  CONNECTION_STRING: "Server=fcg-games.c1k0ou644rxp.sa-east-1.rds.amazonaws.com;Database=usersdb;User Id=postgres;Password=administrator;"
  JWT_SECRET: "CHAVE_SUPER_SECRETA_123456789101"
  